### ISSUE TITLE
Error: Cannot find module 'package-json-versionify' from ...

### ISSUE THREAD

**Issue by SungjungKim** [feross/instant.io#114]
Hi @feross 

I'm trying to install webTorrent client. But there is small problem like below.

I got the following error code after `npm start` and I typed the `npm install package-json-versionify` command. 
But problem is still that.

Any idea what could fix it?

```
Error: Cannot find module 'package-json-versionify' from '/root/myGit/instant.io/node_modules/webtorrent'
    at /root/myGit/instant.io/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/root/myGit/instant.io/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/root/myGit/instant.io/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/root/myGit/instant.io/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/root/myGit/instant.io/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /root/myGit/instant.io/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/root/.nvm/versions/v4.4.7/bin/node" "/root/.nvm/versions/v4.4.7/bin/npm" "run" "build-js"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! instant.io@1.0.0 build-js: `browserify client > static/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the instant.io@1.0.0 build-js script 'browserify client > static/bundle.js'.
npm ERR! This is most likely a problem with the instant.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify client > static/bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs instant.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls instant.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/myGit/instant.io/npm-debug.log

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/root/.nvm/versions/v4.4.7/bin/node" "/root/.nvm/versions/v4.4.7/bin/npm" "run" "build"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! instant.io@1.0.0 build: `npm run build-css && npm run build-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the instant.io@1.0.0 build script 'npm run build-css && npm run build-js'.
npm ERR! This is most likely a problem with the instant.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-css && npm run build-js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs instant.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls instant.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/myGit/instant.io/npm-debug.log

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/root/.nvm/versions/v4.4.7/bin/node" "/root/.nvm/versions/v4.4.7/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! instant.io@1.0.0 start: `npm run build && node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the instant.io@1.0.0 start script 'npm run build && node server'.
npm ERR! This is most likely a problem with the instant.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs instant.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls instant.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/myGit/instant.io/npm-debug.log
```

**Comment by feross** [comment]
I suggest running `rm -rf node_modules/ && npm cache clean && npm install` once more. Can't think of why this one package would be missing for you.
