### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by burtonsamograd** [feross/instant.io#126]
I'm not seeing a ./lib directory from my clone:

NODE_ENV=production npm start
Error: Cannot find module './lib/mediaType'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadModule (/root/instant.io/node_modules/negotiator/index.js:114:16)
    at Negotiator.mediaTypes (/root/instant.io/node_modules/negotiator/index.js:76:52)
    at Accepts.type.Accepts.types (/root/instant.io/node_modules/accepts/index.js:100:33)
    at IncomingMessage.req.accepts (/root/instant.io/node_modules/express/lib/request.js:128:23)
    at ServerResponse.res.format (/root/instant.io/node_modules/express/lib/response.js:621:11)
    at ServerResponse.redirect (/root/instant.io/node_modules/express/lib/response.js:877:8)
Error: Failed to lookup view "error" in views directory "/root/instant.io/server/views"
    at EventEmitter.render (/root/instant.io/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/root/instant.io/node_modules/express/lib/response.js:960:7)
    at /root/instant.io/server/index.js:162:19
    at Layer.handle_error (/root/instant.io/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/root/instant.io/node_modules/express/lib/router/index.js:310:13)
    at /root/instant.io/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/root/instant.io/node_modules/express/lib/router/index.js:330:12)
    at next (/root/instant.io/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/root/instant.io/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/root/instant.io/node_modules/express/lib/router/index.js:310:13)

**Comment by feross** [comment]
The error starts at `Error: Failed to lookup view "error" in views directory "/root/instant.io/server/views"`

Do you have a file named `error.pug` inside the `/root/instant.io/server/views` folder?

**Comment by burtonsamograd** [comment]
Yes, I do. 

    extends layout
    block body
      h1 Error
      h2= message

**Comment by feross** [comment]
I can't think of any reason you would get this error. Your git clone or npm install probably got messed up somehow. Or there's a permission issue and the node process can't read the necessary files. 

I would do a fresh clone, and a fresh npm install.

I don't think this is an issue with instant.io.
